services:
  client:
    build: .
    container_name: mcp_client
    volumes:
      - .:/app
    environment:
      OLLAMA_MODEL_NAME: "qwen3:8b"
      OLLAMA_BASE_URL: "http://host.docker.internal:11434"
      MCP_SERVER_URL: "http://host.docker.internal:8160/mcp"